import { PLACEHOLDER_IMAGE_URL } from "@src/constants";
import {
  eventHasLimitedAvailability,
  useHonestActor,
} from "@src/context/HonestActor";
import DfinityLogo from "@src/ui/logos/DfinityLogo";
import { Preloader } from "@src/ui/progress/Preloader";
import { useActorQuery } from "@src/utils/ActorUtils";
import { formatFractionalICP } from "@src/utils/Formatting";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import type { Event, Universe } from "../../../declarations/honest/honest.did";

const Home: NextPage = () => {
  const honest = useHonestActor();
  const eventsResult = useActorQuery<Event[]>({
    actor: honest,
    method: "getEvents",
  });

  const universesResult = useActorQuery<Universe[]>({
    actor: honest,
    method: "getUniverses",
  });

  if (eventsResult.loading) return <Preloader />;

  const events = eventsResult.data || [];
  const universes = universesResult.data || [];

  return (
    <div className="w-full max-w-6xl m-auto">
      <Head>
        <title>Honest Ticket Machine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="p-8 mt-16 mb-24 w-full bg-cover">
        <div className="prose dark:prose-invert">
          <h1>Honest Ticket Machine</h1>

          <p>
            Built fully on-chain. Powered by{" "}
            <DfinityLogo className="inline-block w-8" />. We are re-imagining
            how creativity can flourish.
          </p>
        </div>
      </section>

      <div className="divider"></div>

      <section>
        <div className="prose dark:prose-invert mb-8 w-full max-w-none">
          <h2>Events</h2>
          <p>Discover events that will supercharge your weekend</p>
        </div>

        <div className="flex flex-row gap-4">
          {events.slice(0, 3).map((event) => (
            <div key={String(event.id)} className="card w-96 bg-slate-800">
              <figure>
                <img src={event.imageUrl[0] || PLACEHOLDER_IMAGE_URL} alt="" />
              </figure>
              <div className="card-body">
                <div className="flex-1">
                  <h3 className="card-title">{event.name}</h3>

                  <p className="mt-2 text-xs">
                    {event.startTime[0]
                      ? new Date(Number(event.startTime[0])).toLocaleDateString(
                          "en-GB",
                          {
                            day: "numeric",
                            year: "numeric",
                            month: "long",
                          }
                        )
                      : "Ongoing"}{" "}
                    {eventHasLimitedAvailability(event) ? (
                      <span className="badge badge-secondary">
                        Limited availability
                      </span>
                    ) : null}
                  </p>

                  <p className="mt-3">
                    {(event.description[0] || "No description provided").slice(
                      0,
                      140
                    )}
                  </p>
                </div>

                <div className="mt-4">
                  <p className="text-sm text-end">
                    from {formatFractionalICP(event.price)}
                  </p>
                </div>

                <div className="card-actions items-center justify-end">
                  <Link href={`/events/${String(event.id)}`}>
                    <a className="btn btn-sm btn-ghost">Find out more</a>
                  </Link>

                  <Link href={`/events/${String(event.id)}`}>
                    <a className="btn btn-primary">Get tickets</a>
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="flex flex-row-reverse mt-8">
          <Link href="/events">
            <a className="btn btn-sm btn-ghost">See all events</a>
          </Link>
        </div>
      </section>

      <div className="divider"></div>

      <section>
        <div className="prose dark:prose-invert mb-8 w-full max-w-none">
          <h2>Universes</h2>
          <p>
            Events are made up of one or a multitude of universes. Discover how
            creators are re-imagining some of your favourite universes
          </p>
        </div>

        <div className="flex flex-row gap-4">
          {universes.slice(0, 3).map((universe) => (
            <div key={String(universe.id)} className="card w-96 bg-slate-800">
              <figure>
                <img
                  src={universe.imageUrl[0] || PLACEHOLDER_IMAGE_URL}
                  alt={universe.name}
                />
              </figure>
              <div className="card-body">
                <h3 className="card-title">{universe.name}</h3>

                {/* <p>
                  <span className="badge">Gaming</span>{" "}
                  <span className="badge">Pixel</span>
                </p> */}

                <p>
                  {(universe.description[0] || "No description provided").slice(
                    0,
                    140
                  )}
                </p>

                <div className="mt-4 card-actions items-center justify-end">
                  <Link href={`/universes/${String(universe.id)}`}>
                    <a className="btn btn-sm btn-primary">Discover events</a>
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="flex flex-row-reverse mt-8">
          <Link href="/universes">
            <a className="btn btn-sm btn-ghost">See all universes</a>
          </Link>
        </div>
      </section>
    </div>
  );
};

export default Home;
